// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.Models;

#nullable disable

namespace ToDo.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20230413175052_ToDo migration created")]
    partial class ToDomigrationcreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("ToDo.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = true,
                            Description = "Finish Web assignment",
                            Title = "ToDo assignment"
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            Description = "Finish ios assignment",
                            Title = "ios assignment"
                        },
                        new
                        {
                            Id = 3,
                            Completed = false,
                            Description = "Finish kotlin assignment",
                            Title = "kotlin assignment"
                        },
                        new
                        {
                            Id = 4,
                            Completed = true,
                            Description = "Finish DBA assignment",
                            Title = "DBA assignment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
